In [ ]:
import numpy as np
import time
import sys
l=range(1000)
print(sys.getsizeof(1)*len(l))
array=np.arange(1000)
print(array.size*array.itemsize)

28000
8000


In [ ]:
import numpy as np
import time 
import sys
SIZE=100000
l1=range(SIZE)
l2=range(SIZE)
a1=np.arange(SIZE)
a2=np.arange(SIZE)
start=time.time()
result=[(x+y)for x,y in zip(l1,l2)]
end=time.time()
print((end-start)*1000)
a=[0]*1000
b=[1]*1000
a1
#print(result)
print("the time taken by python list took:",(time.time()start)*1000)
start =time.time()
result=a1+a2


SyntaxError: ignored

In [ ]:
import numpy as np
import sys



a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1-a2)
print(a2-a1)
print(a1*a2)
print(a1/a2)

[-3 -3 -3]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
a1=np.array([[11,12],[13,14],[15,16]])
print(a1)
a2=np.array([[1,2],[3,4],[5,6]])
print(a2)
a1.ndim



[[11 12]
 [13 14]
 [15 16]]
[[1 2]
 [3 4]
 [5 6]]


2

In [ ]:
a2.ndim

2

In [ ]:
a1.itemsize

8

In [ ]:
a2.itemsize

8

In [ ]:
print(a1.dtype)
print(a2.dtype)


int64
int64


In [ ]:
a4=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
print(a4.itemsize)
print(a4[0])
a4


8
[1. 2.]


array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
import numpy as np
a10001=np.array([[1,2],[3,4],[23,12]])
a10001.size

6

In [ ]:
a4.shape

(3, 2)

In [ ]:
#np.zeros

a5=np.zeros((3,4))
a5


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a10000=np.ones((3,4))
a1111=np.ones((3,4))
a1111*a10000

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a6=np.zeros(np.shape(a4))


a6

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
a100=np.ones((3,4))
a100*a5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a7=np.ones(np.shape(a4))
a7

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a6+a7

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#arange() function
a8=np.arange(3,4,6)
a8

array([3])

In [ ]:
a9=np.arange(1,20,2)
a10=np.arange(1,20,5)
print(a9)
print(a10)

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  6 11 16]


In [ ]:
#linspace()function
np.linspace(1,10,1000)



array([ 1.        ,  1.00900901,  1.01801802,  1.02702703,  1.03603604,
        1.04504505,  1.05405405,  1.06306306,  1.07207207,  1.08108108,
        1.09009009,  1.0990991 ,  1.10810811,  1.11711712,  1.12612613,
        1.13513514,  1.14414414,  1.15315315,  1.16216216,  1.17117117,
        1.18018018,  1.18918919,  1.1981982 ,  1.20720721,  1.21621622,
        1.22522523,  1.23423423,  1.24324324,  1.25225225,  1.26126126,
        1.27027027,  1.27927928,  1.28828829,  1.2972973 ,  1.30630631,
        1.31531532,  1.32432432,  1.33333333,  1.34234234,  1.35135135,
        1.36036036,  1.36936937,  1.37837838,  1.38738739,  1.3963964 ,
        1.40540541,  1.41441441,  1.42342342,  1.43243243,  1.44144144,
        1.45045045,  1.45945946,  1.46846847,  1.47747748,  1.48648649,
        1.4954955 ,  1.5045045 ,  1.51351351,  1.52252252,  1.53153153,
        1.54054054,  1.54954955,  1.55855856,  1.56756757,  1.57657658,
        1.58558559,  1.59459459,  1.6036036 ,  1.61261261,  1.62

In [ ]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
a11=np.array([[1,2],[3,4],[5,6]])
np.shape(a11)

(3, 2)

In [ ]:
#reshape


a12=a11.reshape(3,2)
a12


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.ravel(a12)
a12

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a11=np.array([[1,2],[3,4],[5,6]])
a12=a11.reshape(2,3)
print(np.ravel(a12))
print(a12)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
#more functions
a13.max()


654

In [ ]:
a13.min()

1

In [ ]:
import numpy
a13=np.array([[1,2],[654,11],[67,3]])
a13.sum()

738

In [ ]:
import numpy as np 
a15=np.sqrt(a13)
a15

array([[ 1.        ,  1.41421356],
       [25.57342371,  3.31662479],
       [ 8.18535277,  1.73205081]])

In [ ]:
a17=np.array([[5,6],[7,8]])
a16=np.array([[3,4],[2,31]])
a16.dot(a17)

array([[ 43,  50],
       [227, 260]])

In [ ]:
#indexing and slicing
n=[6,7,8]
n[0:2]

[6, 7]

In [ ]:
n[-1]


8

In [ ]:
a=np.array([6,7,8])
a[0:2]

array([6, 7])

In [ ]:
a=np.array([[6,7,8],[1,2,3]])
a[1,2]
a[0:2]

array([[6, 7, 8],
       [1, 2, 3]])

In [ ]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a[1,2]
a[0:2]


array([[6, 7, 8],
       [1, 2, 3]])

In [ ]:
a[0:2,2]

array([8, 3])

In [ ]:
a.max()

9

In [ ]:
a.min()

1

In [ ]:
a.sum()

41

In [ ]:
a.mean()

4.555555555555555

In [ ]:
a[0:3,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [ ]:
a[1:100:1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [ ]:
#iteration 
for row in a:
  print(row)


[6 7 8]
[1 2 3]
[9 3 2]


In [ ]:
for row in a:
  for item in row:
    print(item)

6
7
8
1
2
3
9
3
2


In [ ]:
for cell in a.flat:
  print(cell)

6
7
8
1
2
3
9
3
2


In [ ]:
a19=np.ravel(a)
a19

array([6, 7, 8, 1, 2, 3, 9, 3, 2])

In [ ]:
a20=a19.reshape(1,9)
for item in a20:
  print(item)

[6 7 8 1 2 3 9 3 2]


In [ ]:
#stacking two array together
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [ ]:
#multiple stacking
c=np.vstack((a,b))
print(c)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [ ]:
a=np.arange(30).reshape(2,15)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [ ]:
#question : find the number of occurances of a sequence of numbers 
arr=numpy.array([[2,8,9,4],
                 [9,4,9,4],
                 [4,5,9,7],
                 [2,9,4,3]])
#counting the sequence
num=repr(arr).count("9, 4")
print(num)

4


In [ ]:
import numpy
count=0
m=int(input("enter the sequence of number:"))
n=int(input("enter the sequence of number:"))
for rows in arr:
  for i in range(len(row)):
    if(row[i]==m and rows[i+1]==n):
      count=count+1
print(count)



enter the sequence of number:12
enter the sequence of number:18
0


In [ ]:
b=a>4
print(type(b))
print(b.dtype)
print(b)

<class 'numpy.ndarray'>
bool
[[False False False False False  True  True  True  True  True  True  True
   True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True]]


In [ ]:
#decomposition abstraction and functions
